Adjust frontend to new API
HackYourCareer/SmartKickers pull request #187
Opened 2022-09-19 12:07 UTC by MichalKalke

Change using statistics to match new API from backend.

2022-09-21 13:44 UTC, mrCherry97 requested changes
![image](https://user-images.githubusercontent.com/46759954/191520463-59e56ba8-73f0-4144-98ab-1aeaac78bbcd.png)

:sadcat:

2022-09-21 13:59 UTC, mrCherry97 approved these changes
Little suggestion, you can disable the button on the view which is chosen, for example when I am on the stats page `Statistics` button could be disable, because I was a little bit confused. Just a suggestion.
![image](https://user-images.githubusercontent.com/46759954/191524529-44f1b92e-5ff6-4cdb-aa6c-c266a0b101da.png)

2022-09-21 14:00 UTC, mrCherry97 commented
![image](https://user-images.githubusercontent.com/46759954/191524809-68445175-0a47-40b3-9bf1-b7efea078f59.png)

2022-09-22 04:31 UTC, MarekMichali approved these changes

2022-09-22 04:32 UTC, merged